### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by SensorsIot** [gcgarner/IOTstack#1]
Hi,
I installed your repo on my new 4G Raspberry and it works! Thank you.
Now I would like to add all my "customization". But of course, I do not want to lose it when I stop the container. Can you help me here?
Regards
Andreas

**Comment by gcgarner** [comment]
Hello Andreas

The docker-compose file uses the "volumes:" command to link files and folder from inside the container to a folder on your pi's sd card. so that when you stop them the next time you start them they should be there.

for example :

```
volumes:
- $PWD/influxdb/data:/var/lib/influxdb
```

"$PWD" is the "present working directory" as in the folder created when you did the git clone command. if you navigate to that folder you should see the directories for the persistent storage.

what you can do is specify a direct path in stead of the $PWD like 

```
volumes:
- /home/pi/DockerStorage/influxdb/data:/var/lib/influxdb
```

here is what is inside my nodered persistent storage I have a folder in my home directory called "dockers"

![image](https://user-images.githubusercontent.com/46672225/62408049-8ae42080-b5c2-11e9-9b2a-c4e3c66d3a88.png)


remember that you need to change the folderfix.sh to match the same path as you chose. I made a small change the the folderfix.sh file to make my file more concistent.

if there is a specific image that does not keep its data let me know, maybe i missed a specific volume.

**Comment by gcgarner** [comment]
When i created the gitignore file i made it exclude the data folders. This was to make sure that if i did a commit none of my data was coming with. (why i chose $PWD in the first place)
If however you want to specific data to stay eg. your grafana plugins and make them part of your git project then you should add them directly

**Comment by SensorsIot** [comment]
I tried now to continue with this project. It is quite hard for me with my current level of knowledge. After a few hours, I got node-red running. But it says, it is based on an unsupported node.js version :-(
Now I would like to configure influxdb. But I do not know how to get terminal access to the container...
Would it be a possibility to have a Skype session with you to get me up to speed? If everything runs I would also like to add a VPN container to get remote access. I think, this would be a neat project for many of us with a home server...
If you want to spend your time, my skype name is spiessa.
