### ISSUE TITLE
enhancement? moving to alpine images?

### ISSUE THREAD

**Issue by echtelerp** [gcgarner/IOTstack#17]
and one more :-) 
you are using the standard images so far. 
this might use a lot of space. 
for most containers, there are alpine based ones out there.

could that be a possible switch at the beginning of your menu?

**Comment by gcgarner** [comment]
I like that idea, great suggestion

**Comment by fragolinux** [comment]
> I like that idea, great suggestion

hi, I'm Antonio, main contributor and active maintainer of Peter Scargill's script :)
i had started a similar project a year ago, then put aside because migrated to Hass.io and its addons: https://github.com/fragolinux/DockerIOT
i'd like to contribute to your project, maybe merging some of the stuff i made at that time... i was trying to do all based on Alpine, and preserving what already works in Pete's script, so even the hardware part (serial, i2c), and the awful to install sqlite in nodered, but as it's used by many...

tell me if and how can i help

**Comment by gcgarner** [comment]
Hello Antonio, I would be glad to collaborate there is a lot of room for improvement and a lot to learn. 

I tried to install sqlite in the standard image and had no success, that's why i dropped it from the selection list. 

I haven't tried any of the Alpine images but if they are available and stable it might be better to swap out all the images unless there are errors. I'd like to incorporate what you already had working.

**Comment by fragolinux** [comment]
contact me on skype, mrsharkit :)

**Comment by echtelerp** [comment]
I would be open to contribute, too. 
I don't use skype but how about a slack channel for contributors?

**Comment by fragolinux** [comment]
as said on skype, if nodered image is based on nodered/node-red then sqlite can be installed with a relative Dockerfile:

`RUN npm install --unsafe-perm node-red-node-sqlite
`

**Comment by gcgarner** [comment]
adding this to #14
