### ISSUE TITLE
How to modify influxdb.conf?

### ISSUE THREAD

**Issue by alexm2901** [gcgarner/IOTstack#202]
Yes I know this is maybe a stupid question - but I am trying hard to lern.
I want to add the db name where udp telegrams go to. According to https://docs.influxdata.com/influxdb/v1.8/supported_protocols/udp/#config-examples 
so i need to activate the udp listener and add the target db. Is this possible or not?
![image](https://user-images.githubusercontent.com/48953289/93522117-4dab3100-f931-11ea-84ef-e08180c8784c.png)

**Comment by Paraphraser** [comment]
Hi @alexm2901 

Please see [This project is dormant](https://github.com/gcgarner/IOTstack/issues/194). It explains why IOTstack activity is now focused on [SensorsIot/IOTstack](https://github.com/SensorsIot/IOTstack).

It's really easy to [migrate](https://github.com/SensorsIot/IOTstack#migrating-from-the-old-repo) from gcgarner/IOTstack to SensorsIot/IOTstack.

Although some people (like me) are still monitoring [gcgarner/IOTstack](https://github.com/gcgarner/IOTstack), you'll probably get better support on [SensorsIot/IOTstack](https://github.com/SensorsIot/IOTstack) and/or by joining the [Discord channel](https://discord.gg/W45tD83) if you have not already done that.

Your question came up once before on Discord. At the time I thought it was a one-off so I didn't try to document the answer. Now that it has come up twice, I've written a [gist](https://gist.github.com/Paraphraser/15483641fc657a147dfae7b03d291bc0) on the topic. I'm hoping it will answer your question. Please let me know if it helps, or if I need to add more to the gist or clarify certain points.

If the gist solves your problem, it would be really helpful if you could remember to close this issue.

If it isn't immediately clear from the gist, when you are working in a Docker environment, any solution that begins with editing `influxdb.conf` is the wrong answer.

Although the approach **could** work - in principle - the problem is that any changes you make would not be persistent. They would be lost the next time the influxdb container was rebuilt. The influx documentation does cover this but it isn't done in a way that helps new users have the "ahah!" moment (and, trust me, I've been down this same rabbit hole). It definitely takes some getting used to.

**Comment by alexm2901** [comment]
Hi @Paraphraser 

Thanks o lot for your quick replay. OK i unterstand now why this works not the old fashioned way. Ill try an of course close this issue.

THX a lot
