### ISSUE TITLE
Openhab General

### ISSUE THREAD

**Issue by Paulf007** [gcgarner/IOTstack#22]
If Openhab and Adminer are selected, Adminer will get port 8080 instead of openhab. 
The https for Opehab(8443) does work, however. Will test Opehab further and report. 
Maybe consider changing the default port to Adminer for another port?
Wish List:
- Consider Loading SAMBA with sharing the `/home/pi/IOTstack/volumes/openhab/conf` folder as these get edited fairly often ( It would then be similar to Openhabian)
- Alternative Owner, Currently it has 9001 as the folder Owner this could be changed so that Pi could be the Owner. 

The rest of Openhab performed as expected. I will run some more Tests but Well Done and Thank you Graham!

**Comment by gcgarner** [comment]
Hi Paul

Well spotted. I think Port conflicts are going to be an issue going ahead. I dropped PiHole and Nginx from the release because they use all the same ports. 

I will change out Adminer to another Port as you suggest, I expect Adminer to get less traffic that OpenHAB.
The file and directory permissions are a bit problematic but i thing we can make it work

**Comment by gcgarner** [comment]
Thanks again @Paulf007, I have added this to the README
