### ISSUE TITLE
Home Assistant Native keeps coming back after removal

### ISSUE THREAD

**Issue by muxa** [gcgarner/IOTstack#235]
I have installed Home Assistant Native (Hass.io) using IOTStack. 
Then I removed it using [official instructions](https://sensorsiot.github.io/IOTstack/Containers/Home-Assistant/#removal)

However after some time (after reboot?) Hass.io came back. Is there way to permanently remove it?

**Comment by Paraphraser** [comment]
Please see [This project is dormant](https://github.com/gcgarner/IOTstack/issues/194).

The above contains a link to a gist with [detailed migration instructions](https://gist.github.com/Paraphraser/107888b746a65d5d8f0e95a681471ebd). It's a bit subtle so I'm repeating it here.

To answer your question, I don't know. I don't run "home" anything so I have no practical knowledge to offer. 

There's a pretty detailed installation sequence [here](https://siytek.com/install-home-assistant-on-raspbian/). If this were my problem (ie you've tried what's in the IOTstack doco and it doesn't work), I'd be working backwards through alternative sources looking for the inverses of various steps. I'd also be looking at how the gcgarner menu installed - did it use pip or some other method? If it used pip, was it plain pip (indicating an installation under user pi) or sudo pip (indicating an installation for the whole machine). Then I'd try (sudo) pip(3) uninstall xxx.

One of the reasons why I don't run home-anything is because every time I have stuck my nose into the issue, I have observed serious futzing with the underlying OS. I added material to a now out-of-date [gist](https://gist.github.com/Paraphraser/55643bd660db46716f6c81266905cae8#hassio-support-optional) so I'd have something to point to when people asked questions on Discord, which were variations on the theme of "I'm trying to install hass.io but...". The whole thing gives me the screaming heebies. The few experiments I've done (eg making sure the steps in the gist actually worked) have always ended in a nuke-and-rebuild of the RPi. You probably don't want to hear this but if you want my honest advice: *nuke-and-rebuild.*
