### ISSUE TITLE
Do not change host name before installing 

### ISSUE THREAD

**Issue by Paulf007** [gcgarner/IOTstack#34]
If you change the hostname before running the docker install command it will not be able to install docker. 
I assume that this could be part of the read me?

**Comment by gcgarner** [comment]
Hi Paul, thanks again for your contributions.

I just tested changing the name. I had burned a new sd card for my 3B last week and changed the name back then. 
I ran the install from the menu and docker install without any issues. 

I know i used raspi-config to do the change. how did you change the name?

**Comment by Paulf007** [comment]
I also used raspi-config. I will need to run a new image again to replicate and will post the results.

**Comment by lnlp** [comment]
@Paulf007 said he changed host name via raspi-config so following should not be an issue in that case but my experience is that changing host name with the hostname command on Raspbian does not work correctly, but changing it using raspi-config does work properly.

**Comment by Paraphraser** [comment]
I’ve done several “from scratch” builds. I wanted to be able to run the RPi4 from a USB-3 SSD and was trying to figure out an optimal path so that I could [document it](https://gist.github.com/Paraphraser/55643bd660db46716f6c81266905cae8) and never have to think about it again. Each time I renamed the Pi using raspi-config, followed by a reboot. The “sudo reboot” immediately after the name change would always complain about not being able to find something to do with the default name but that was the only hassle. After that everything Including installing IOTStack just worked.

**Comment by gcgarner** [comment]
I did a build of a zero w yesterday, I changes the name and on the sudo reboot (all of this was done over ssh because i was to lazy to go find my mini hdmi cable) it also gave an error regarding not being able to resolve the name. However when it rebooted it had the new name and it went on with out a problem. Do you think its a problem? Do you not think its the ssh channel that gets a name conflict?

**Comment by Paraphraser** [comment]
My instinct is that it’s probably nothing other than what it seems - logged in under one hostname, the rug pulled from under it by the rename, grizzle at the logout forced by the shutdown. My only lingering doubt is why the PiHole URL without the /admin suffix doesn’t work **and** is also grizzling about names. I don’t see why they should be related - none of the Docker stuff is being installed until long after the rename (in my case, anyway). That really only leaves two possibilities: a hard-coded reference somewhere to the default name (which seems unlikely), or something wrong with the supplied PiHole install script.

Sorry that this case is now getting tangled up with #60. I was trying to reassure Paulf007 that renaming via raspi-config did work, at least for me.

**Comment by gcgarner** [comment]
@Paraphraser i just did a stupid test on pihole now, i changed its port 80## to port 80. now when i navigate to my IP is shows the correct page asking to redirect to the admin page. This is on my Pi running from my project

![image](https://user-images.githubusercontent.com/46672225/68595430-17e02500-04a2-11ea-86ac-267f3d146fdf.png)

 i was looking through some issues on piholes github page and I saw some references to reverse proxies not redirecting when you change the port away from 80.

**Comment by gcgarner** [comment]
this doesnt seem to be an issue and pihole conversation merged with #72
