### ISSUE TITLE
Container name hassio appears to be incorrect

### ISSUE THREAD

**Issue by lnlp** [gcgarner/IOTstack#49]
First a thanks for your IOTstack efforts.

By default hassio is a combination of a Home Assistant Docker container running on HassOS. It is available as downloadable (SD card) image from GitHub via https://www.home-assistant.io/hassio/installation/.  Included in hassio's UI is the possibility to download add-ons from the hassio add-on store.

If I understand correctly IOTstack's Home Assistant Docker container is not hassio.
If so then the container name 'hassio' is very confusing and should therefore be renamed to 'homeassistant' instead.

According to https://www.home-assistant.io/hassio/installation/ and
https://github.com/home-assistant/hassio-installer/blob/master/hassio_install.sh
it should be possible to do an alternative install of hassio on Raspbian.
But because IOTstack's Home Assistant container has the standard Home Assistant UI and not hassio's UI (no add-on store in menu) my assumption is that IOTstack currently does not use hassio.

**Comment by gcgarner** [comment]
Hi, you are correct. The container was home assistant not hassio. I corrected this last night. The new version has a separate installation for hassio and it works with its own service

**Comment by lnlp** [comment]
Thanks, I noticed it on the Wiki few hours after you had updated it.

I have installed the new version which now indeed is hassio and consists of 3 containers.
While I think it is nice that it is now a full hassio implementation, hassio run on top of Alpine which means an additional OS layer which also takes more resources.

I like IOTstack's concept of ./volumes where data from each container is externally stored in a central location. Because the new hassio is not managed by IOTstack this is no longer the case.
Do you have any idea how the same construction can be implemented on hassio?
_(I added two soft links for Volumes and Backups so they point to a separate disk partition that I have mounted as /data. This way the data is even physically separated from the host OS and I would like to use this for hassio too)._

What is yet unclear to me is how hassio maintains its add-ons from the store. Are these add-ons installed inside (one of) the (three) homeassistant container(s) or will these be installed as separate docker containers (e.g. for add-ons like Mosquitto and Grafana)?
Then there is also the issue that some of the hassio add-ons are already installed as services in IOTstack (and in future new services may be added to IOTstack that are also available in hassio). Of course only one single instance of those services should be used/installed, but give you give any information on the implication that services exist/can be installed both as part of IOTstack and hassio and can you give any best practices for how to deal with this from IOTstack perspective?

**Comment by gcgarner** [comment]
There is an option for specifying the "volumes" directory for hassio. The default is somewhere in /usr/share/hassio I think. The installer documentation is [here](https://github.com/home-assistant/hassio-installer)

I literally only heard about hassio when a community member submitted "home assistant" as a pull request. I'm going to have to play around with the utility to find out more about it.

In terms of the overlap, this will come down to the user. One person may only want an mqtt server and influxdb on one Pi and run the other services on a different device. You may not want the "bulk" of hassio. However if you want hassio anyways then install the services you want inside it and let hassio manage everything for you. I think managing your own stack gives you slightly more flexibility even if is does require you to be a little more hands on.

Personally I do like the openness of my stack, you can see exactly what is installed and where, nothing is hidden.

There is another dilema for me regarding changing the data volume, hassio's documentation is geared to their layout, if I change it then it may confuse a very novice user because they cant find what is in the support documentation. I'm already preparing to make a wiki entry on how to reset your password for example.

**Comment by lnlp** [comment]
Thanks. I will have a look at that documentation.

**Comment by gcgarner** [comment]
The advantages of hassio are that you get a polished integrated environment to work in. I has quite a lot of containers. The downside looks like it takes quite a while to setup.

The advantage of IOTstack is that it has rapid deployment and you can hack it to what you need. The major downside is you need to learn a little bit about docker along the way.

Both achieve roughly the same goal. They pull a docker image and start/manage it. The only thing that you cant do is run two containers that do the same thing. There will be a port conflict and one of the services will fail.

My advice is that if you are using hassio anyways rather use their versions of the containers, you get the benefit of their management tools

**Comment by lnlp** [comment]
> You can consider using the hassio image as well

I had hassio installed from their SD card image just before I discovered IOTstack, but I like the benefit of having a full Raspbian (Lite) host OS instead of a barebones Linux version.

**Comment by gcgarner** [comment]
glad i could help
