### ISSUE TITLE
log2ram

### ISSUE THREAD

**Issue by fxg90** [gcgarner/IOTstack#8]
Just for understanding it right: Will it be enough to have log2ram on the root system?
Won't each container log for itself?

**Comment by gcgarner** [comment]
log2ram replaces the /var/log folder with a ramdrive then syncs those changes to disk on a schedule. This reduces the total writes to the sd card.

The containers don't log to /var/log, they log to their own internal logs

**Comment by gcgarner** [comment]
Because each container has its own log that writes to disk inside their respective container it may be worthwhile to map them securely into /var/log to get full benefit of log2ram

**Comment by fxg90** [comment]
That's what i was asking for, Thanks. I just getting into Docker, may i find out how to map the logs into /var/log

**Comment by gcgarner** [comment]
Each container will differ as to where they store their logs. I used the script "./services/nodered/terminal.sh" to open the shell for nodered. Doing a "ls /var/log" inside nodered shows that its "standard" log is empty. I would assume that the standard log would be empty and containers would do minimal logging.

First you would need to make a subfolder in /var/log that you want to share. Don't directly map your /var/log because you don't want to unnecessarily expose your sensitive data to a container.

If you do find the log for a container you can edit the docker-compose.yml file and under the volumes add

volumes:
  - /var/log/MYLOG:/path/to/log/inside/container

**Comment by fxg90** [comment]
Thank you!
