### ISSUE TITLE
In Portainer, all IPs for containers are 0.0.0.0

### ISSUE THREAD

**Issue by ronnyandre** [gcgarner/IOTstack#96]
In the container list, the column with Published Ports have a lot of forwarded ports with links.

All the links are pointing to 0.0.0.0:[PORT] - Is this normal, or do I need to set the IP to the host somewhere manually?

**Comment by gcgarner** [comment]
i never noticed this before because i never used that.

you can fix that in the endpoint config

![image](https://user-images.githubusercontent.com/46672225/69695462-26a31a80-10e5-11ea-991d-24b7282c8963.png)

and set the public IP

![image](https://user-images.githubusercontent.com/46672225/69695485-3c184480-10e5-11ea-85f7-8385ac339d76.png)

I'll update this in the wiki

**Comment by gcgarner** [comment]
wiki updated
